# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_update_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["name", "username"]},),
    ]
