# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='environment_secret_keys',
            field=models.CharField(blank=True, help_text='Comma-separated list of keys in the environment that are set but not read (use for tokens/keys).', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='repository',
            field=models.CharField(default='bla', help_text='The repository/name of the image.', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='project',
            field=models.ForeignKey(help_text='Project in which this container belongs', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='projectroles.Project'),
        ),
    ]
