# Generated by Django 3.1.8 on 2021-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20210408_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='environment',
            field=models.JSONField(help_text='The environment variables to use'),
        ),
    ]
