# Generated by Django 3.2.5 on 2021-07-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20210630_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerActionLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateTimeField(auto_now=True, help_text='DateTime of action')),
                ('action', models.CharField(choices=[('start', 'start'), ('restart', 'restart'), ('stop', 'stop'), ('pause', 'pause'), ('unpause', 'unpause')], max_length=32)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_lock', to='containers.container')),
            ],
        ),
    ]
