# Generated by Django 3.1.8 on 2021-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20210409_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerbackgroundjob',
            old_name='process',
            new_name='container',
        ),
        migrations.AddField(
            model_name='container',
            name='image_id',
            field=models.CharField(blank=True, help_text='Image ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='tag',
            field=models.CharField(default='', help_text='The tag of the image.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('restarting', 'restarting'), ('running', 'running'), ('paused', 'paused'), ('exited', 'exited'), ('dead', 'dead'), ('deleting', 'deleting'), ('deleted', 'deleted'), ('pulling', 'pulling'), ('initial', 'initial'), ('failed', 'failed')], default='pulling', help_text='The state of the container.', max_length=32),
        ),
    ]
