# Generated by Django 3.1.8 on 2021-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_auto_20210414_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_path',
            field=models.CharField(blank=True, help_text='Path segment of the container URL', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('restarting', 'restarting'), ('running', 'running'), ('paused', 'paused'), ('exited', 'exited'), ('dead', 'dead'), ('deleting', 'deleting'), ('deleted', 'deleted'), ('pulling', 'pulling'), ('initial', 'initial'), ('failed', 'failed')], default='initial', help_text='The state of the container.', max_length=32),
        ),
    ]
