# Generated by Django 3.1.8 on 2021-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_containerlogentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerlogentry',
            name='process',
            field=models.CharField(choices=[('object', 'object'), ('task', 'task'), ('proxy', 'proxy'), ('docker', 'docker'), ('action', 'action')], default='object', help_text='Process that reports the entry', max_length=32),
        ),
    ]
