# Generated by Django 3.2.5 on 2021-07-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0019_project_public_guest_access'),
        ('containers', '0006_give_titles_in_container_a_unique_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='container',
            unique_together={('project', 'title')},
        ),
    ]
