# Generated by Django 3.2.5 on 2021-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_alter_container_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeractionlock',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('restart', 'restart'), ('stop', 'stop'), ('pause', 'pause'), ('unpause', 'unpause'), ('delete', 'delete')], max_length=32),
        ),
        migrations.AlterField(
            model_name='containerbackgroundjob',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('restart', 'restart'), ('stop', 'stop'), ('pause', 'pause'), ('unpause', 'unpause'), ('delete', 'delete')], max_length=32),
        ),
    ]
