# Generated by Django 3.1.8 on 2021-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_containerlogentry_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerlogentry',
            name='date_docker_log',
            field=models.DateTimeField(blank=True, help_text='DateTime of Docker log entry', null=True),
        ),
    ]
