# Generated by Django 3.2.5 on 2021-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_auto_20210729_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='inactivity_threshold',
            field=models.IntegerField(default=7, help_text='Number of days the container is allowed to run without proxy access.'),
        ),
    ]
