# Generated by Django 3.1.8 on 2021-04-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_containerlogentry_date_docker_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='date_last_logs',
        ),
    ]
