# Generated by Django 3.1.8 on 2021-05-19 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('containers', '0009_remove_container_date_last_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerbackgroundjob',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('restart', 'restart'), ('stop', 'stop'), ('pause', 'pause'), ('unpause', 'unpause')], max_length=32),
        ),
        migrations.AlterField(
            model_name='containerbackgroundjob',
            name='container',
            field=models.ForeignKey(help_text='The container that the job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='containerbackgroundjob', to='containers.container'),
        ),
        migrations.AlterField(
            model_name='containerlogentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who caused the log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
