# Generated by Django 3.2.8 on 2021-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0009_container_inactivity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_ip',
            field=models.CharField(blank=True, help_text='Container IP', max_length=16, null=True),
        ),
    ]
