# Generated by Django 3.1.8 on 2021-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_auto_20210519_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='max_retries',
            field=models.IntegerField(default=5, help_text='Maximal number of retries for an action in case of failure'),
        ),
        migrations.AddField(
            model_name='containerbackgroundjob',
            name='retries',
            field=models.IntegerField(default=0, help_text='Number of retries for the action.'),
        ),
    ]
