# Generated by Django 3.1.8 on 2021-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0011_auto_20210521_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='date_last_status_update',
            field=models.DateTimeField(blank=True, help_text='DateTime of last status update', null=True),
        ),
    ]
