# Generated by Django 5.2.11 on 2026-03-18 15:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0012_alter_containerbackgroundjob_bg_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="environment",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="The environment variables to use",
                null=True,
            ),
        ),
    ]
