# Generated by Django 3.1.8 on 2021-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0012_container_date_last_status_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='timeout_exceeded',
        ),
        migrations.AlterField(
            model_name='container',
            name='timeout',
            field=models.IntegerField(default=60, help_text='Interval in seconds for any Docker action to be performed.'),
        ),
    ]
