# Generated by Django 3.1.8 on 2021-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_auto_20210601_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='host_port',
            field=models.IntegerField(blank=True, help_text='Port of the container on the host', null=True, unique=True),
        ),
    ]
