# Generated by Django 5.2.12 on 2026-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_alter_container_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='volume_name',
            field=models.UUIDField(default=None, help_text='Name of the Docker volume associated to the container', null=True, unique=True),
        ),
    ]
