# Generated by Django 5.2.11 on 2026-04-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0013_alter_container_environment'),
        ('containertemplates', '0007_auto_20220414_1148'),
        ('projectroles', '0039_remove_project_public_guest_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='registry_password',
            field=models.CharField(
                blank=True,
                help_text='The password or token for the container registry, if it is a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='container',
            name='registry_user',
            field=models.CharField(
                blank=True,
                help_text='The user name for the container registry, if it is a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('registry_user__isnull', True),
                        ('registry_user__isnull', True),
                    ),
                    models.Q(
                        ('registry_user__isnull', False),
                        ('registry_user__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='containers_container_registry_credentials_not_null_individually',
            ),
        ),
    ]
