# Generated by Django 5.2.12 on 2026-05-14 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0014_container_volume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='volume_name',
            field=models.UUIDField(default=uuid.uuid4, help_text='Name of the Docker volume associated to the container', null=True, unique=True),
        ),
    ]
