# Generated by Django 5.2.12 on 2026-05-23 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0015_container_volume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='date_last_status_update',
        ),
        migrations.AddField(
            model_name='container',
            name='date_last_access',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='DateTime of latest app access',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(
                choices=[
                    ('created', 'created'),
                    ('restarting', 'restarting'),
                    ('running', 'running'),
                    ('paused', 'paused'),
                    ('exited', 'exited'),
                    ('dead', 'dead'),
                    ('deleting', 'deleting'),
                    ('deleted', 'deleted'),
                    ('pulling', 'pulling'),
                    ('initial', 'initial'),
                    ('failed', 'failed'),
                    ('terminated', 'terminated'),
                ],
                default='initial',
                help_text='The state of the container.',
                max_length=32,
            ),
        ),
    ]
