# Generated by Django 5.2.11 on 2026-05-15 08:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0015_alter_container_volume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='environment',
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='The environment variables to use, as a JSON object where the keys are variable names.',
                null=True,
            ),
        ),
    ]
