# Generated by Django 5.2.16 on 2026-08-06 08:05

import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'containers',
            '0016_remove_container_date_last_status_update_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=martor.models.MartorField(
                blank=True,
                help_text='Description of the container (Markdown supported).',
                null=True,
            ),
        ),
    ]
