# Generated by Django 5.2.12 on 2026-05-23 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0016_alter_container_volume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='date_last_status_update',
        ),
        migrations.AddField(
            model_name='container',
            name='date_last_access',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='DateTime of latest app access',
            ),
            preserve_default=False,
        ),
    ]
