# Generated by Django 5.2.12 on 2026-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'containers',
            '0016_remove_container_date_last_status_update_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.CharField(
                choices=[
                    ('created', 'created'),
                    ('restarting', 'restarting'),
                    ('running', 'running'),
                    ('paused', 'paused'),
                    ('exited', 'exited'),
                    ('dead', 'dead'),
                    ('deleting', 'deleting'),
                    ('deleted', 'deleted'),
                    ('pulling', 'pulling'),
                    ('initial', 'initial'),
                    ('failed', 'failed'),
                    ('terminated', 'terminated'),
                ],
                default='initial',
                help_text='The state of the container.',
                max_length=32,
            ),
        ),
    ]
