# Generated by Django 5.2.11 on 2026-05-15 15:38

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0016_alter_container_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRemoteMount',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'volume_name',
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text='Name of the Docker volume associated to the container.',
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'source',
                    models.URLField(help_text='URL of the data to download.'),
                ),
                (
                    'dest',
                    models.CharField(
                        help_text='Path in the container where the data will be found.',
                        max_length=4096,
                    ),
                ),
                (
                    'dirty',
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text='Whether the data should be re-downloaded.',
                    ),
                ),
                (
                    'date_downloaded',
                    models.DateTimeField(
                        blank=True,
                        help_text='DateTime of the last download.',
                        null=True,
                    ),
                ),
                (
                    'container',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='remote_mounts',
                        to='containers.container',
                    ),
                ),
            ],
        ),
    ]
