# Generated by Django 5.2.17 on 2026-08-21 08:33

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0017_alter_container_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='volume_name',
        ),
        migrations.AlterField(
            model_name='container',
            name='environment',
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='The environment variables to use, as a JSON object where the keys are the variable names.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='container',
            name='registry_password',
            field=models.CharField(
                blank=True,
                help_text='The password or token for the container registry, if it is e.g. a private GitLab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='container',
            name='registry_user',
            field=models.CharField(
                blank=True,
                help_text='The user name for the container registry, if it is e.g. a private GitLab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='ContainerRemoteMount',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'volume_name',
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text='Name of the Docker volume associated to the container.',
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'source',
                    models.URLField(
                        blank=True,
                        help_text='URL of the data to download.',
                        null=True,
                    ),
                ),
                (
                    'dest',
                    models.CharField(
                        help_text='Directory in the container where the data will be found.',
                        max_length=4096,
                    ),
                ),
                (
                    'dirty',
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text='Whether the data should be re-downloaded.',
                    ),
                ),
                (
                    'date_last_update',
                    models.DateTimeField(
                        blank=True,
                        help_text='DateTime of the last download.',
                        null=True,
                    ),
                ),
                (
                    'container',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='remote_mounts',
                        to='containers.container',
                    ),
                ),
            ],
        ),
    ]
