# Generated by Django 5.2.17 on 2026-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0018_remove_container_volume_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerremotemount',
            name='source',
            field=models.URLField(
                blank=True,
                help_text='URL of the data to download.',
                max_length=4096,
                null=True,
            ),
        ),
    ]
