# Generated by Django 5.2.16 on 2026-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containers', '0019_alter_containerremotemount_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='host_port',
            field=models.IntegerField(
                blank=True,
                help_text='Port of the container on the host (if omitted, a random one will be chosen)',
                null=True,
            ),
        ),
    ]
