# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 07:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import dockerapps.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bgjobs", "0005_auto_20190128_1210"),
        ("projectroles", "0010_update_appsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "info"), ("warning", "warning"), ("error", "error")],
                        default="info",
                        help_text="Level of log entry",
                        max_length=32,
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ContainerStateControlBackgroundJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Background job specialization SODAR UUID",
                        unique=True,
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dockerapps_containerstatecontrolbackgroundjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
            ],
            bases=(dockerapps.models.JobModelMessageMixin2, models.Model),
        ),
        migrations.CreateModel(
            name="DockerImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Barcodeset SODAR UUID", unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Title of the docker app", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the docker app", null=True
                    ),
                ),
                (
                    "repository",
                    models.CharField(help_text="The repository/name of the image.", max_length=512),
                ),
                ("tag", models.CharField(help_text="The tag of the image", max_length=128)),
                (
                    "image_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal ID of the Docker image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("pulling", "pulling"),
                            ("idle", "idle"),
                            ("deleting", "deleting"),
                            ("failed", "failed"),
                        ],
                        default="initial",
                        help_text="The state of the image.",
                        max_length=64,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",)},
        ),
        migrations.CreateModel(
            name="DockerProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True, help_text="Container ID", max_length=128, null=True
                    ),
                ),
                (
                    "internal_port",
                    models.IntegerField(default=80, help_text="Server port within the container"),
                ),
                (
                    "host_port",
                    models.IntegerField(
                        help_text="The port of the container on the host", unique=True
                    ),
                ),
                (
                    "do_run",
                    models.BooleanField(
                        default=False, help_text="Whether or not the container should be running"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("starting", "starting"),
                            ("running", "running"),
                            ("stopping", "stopping"),
                            ("failed", "failed"),
                        ],
                        default="idle",
                        help_text="The state of the container.",
                        max_length=64,
                    ),
                ),
                (
                    "environment",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The environment variables to use."
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Docker container that this image is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dockerapps.DockerImage",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",)},
        ),
        migrations.CreateModel(
            name="ImageBackgroundJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Background job specialization SODAR UUID",
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("pull", "pull"), ("delete", "delete")], max_length=32
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dockerapps_imagebackgroundjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="The docker image that the job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dockerapps.DockerImage",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            bases=(dockerapps.models.JobModelMessageMixin2, models.Model),
        ),
        migrations.CreateModel(
            name="ImageLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "info"), ("warning", "warning"), ("error", "error")],
                        default="info",
                        help_text="Level of log entry",
                        max_length=32,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="dockerapps.DockerImage",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="containerstatecontrolbackgroundjob",
            name="process",
            field=models.ForeignKey(
                help_text="The docker process that the job belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="dockerapps.DockerProcess",
            ),
        ),
        migrations.AddField(
            model_name="containerstatecontrolbackgroundjob",
            name="project",
            field=models.ForeignKey(
                help_text="Project in which this objects belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="projectroles.Project",
            ),
        ),
        migrations.AddField(
            model_name="containerlogentry",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="dockerapps.DockerProcess",
            ),
        ),
    ]
