# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projectroles", "0010_update_appsetting")]

    operations = [
        migrations.CreateModel(
            name="DockerImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Barcodeset SODAR UUID", unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Title of the docker app", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the docker app", null=True
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        blank=True,
                        help_text="The repository/name of the image.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, help_text="The tag of the image", max_length=128, null=True
                    ),
                ),
                (
                    "image_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal ID of the Docker image",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("pulling", "pulling"),
                            ("deleting", "deleting"),
                            ("failed", "failed"),
                        ],
                        help_text="The state of the image.",
                        max_length=64,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",)},
        ),
        migrations.CreateModel(
            name="DockerProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True, help_text="Container ID", max_length=128, null=True
                    ),
                ),
                (
                    "internal_port",
                    models.IntegerField(help_text="Server port within the container"),
                ),
                (
                    "host_port",
                    models.IntegerField(help_text="The port of the container on the host"),
                ),
                (
                    "do_run",
                    models.BooleanField(
                        default=False, help_text="Whether or not the container should be running"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("starting", "starting"),
                            ("running", "running"),
                            ("stopping", "stopping"),
                            ("failed", "failed"),
                        ],
                        help_text="The state of the container.",
                        max_length=64,
                    ),
                ),
                (
                    "environment",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The environment variables to use."
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Docker container that this image is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dockerapps.DockerImage",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",)},
        ),
    ]
