# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projectroles", "0006_add_remote_projects")]

    operations = [
        migrations.CreateModel(
            name="DockerApp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Barcodeset SODAR UUID", unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Title of the docker app", max_length=100)),
                (
                    "description",
                    models.TextField(help_text="Description of the docker app", null=True),
                ),
                (
                    "image_id",
                    models.CharField(help_text="Internal ID of the Docker image", max_length=100),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
        )
    ]
