# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="dockerimage",
            name="repository",
            field=models.CharField(help_text="The repository/name of the image.", max_length=512),
        ),
        migrations.AlterField(
            model_name="dockerimage",
            name="tag",
            field=models.CharField(help_text="The tag of the image", max_length=128),
        ),
    ]
