# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="dockerimage",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Password to use for logging into registry; optional",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dockerimage",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="User name to use for logging into registry; optional",
                max_length=1024,
                null=True,
            ),
        ),
    ]
