# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="dockerapp",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the docker app", null=True
            ),
        )
    ]
