# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0002_auto_20190311_1422")]

    operations = [
        migrations.AddField(
            model_name="dockerapp",
            name="port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Port used by the Docker image", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="dockerapp",
            name="state",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("starting", "starting"),
                    ("running", "running"),
                    ("failed", "failed"),
                ],
                default="idle",
                help_text="The current docker container state",
                max_length=32,
            ),
        ),
    ]
