# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0004_auto_20190314_0824")]

    operations = [
        migrations.AlterField(
            model_name="dockerapp",
            name="host_port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Port used by the Docker image", null=True
            ),
        )
    ]
