# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bgjobs", "0005_auto_20190128_1210"),
        ("dockerapps", "0005_deleteimagebackgroundjob_pullimagebackgroundjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageBackgroundJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Background job specialization SODAR UUID",
                        unique=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("pull", "pull"), ("delete", "delete")], max_length=32
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dockerapps_imagebackgroundjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="The docker image that the job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dockerapps.DockerImage",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="pullimagebackgroundjob", name="bg_job"),
        migrations.RemoveField(model_name="pullimagebackgroundjob", name="image"),
        migrations.DeleteModel(name="PullImageBackgroundJob"),
    ]
