# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0006_auto_20190627_2048")]

    operations = [
        migrations.RemoveField(model_name="deleteimagebackgroundjob", name="bg_job"),
        migrations.RemoveField(model_name="deleteimagebackgroundjob", name="process"),
        migrations.DeleteModel(name="DeleteImageBackgroundJob"),
    ]
