# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0006_auto_20190320_1455")]

    operations = [
        migrations.AlterField(
            model_name="dockerapp",
            name="image_id",
            field=models.CharField(
                blank=True, help_text="Internal ID of the Docker image", max_length=100, null=True
            ),
        )
    ]
