# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dockerapps.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bgjobs", "0005_auto_20190128_1210"),
        ("dockerapps", "0008_auto_20190715_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerStateControlBackgroundJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Background job specialization SODAR UUID",
                        unique=True,
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dockerapps_containerstatecontrolbackgroundjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        help_text="The docker process that the job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dockerapps.DockerProcess",
                    ),
                ),
            ],
            bases=(dockerapps.models.JobModelMessageMixin2, models.Model),
        )
    ]
