# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dockerapps", "0010_auto_20190716_0741")]

    operations = [
        migrations.AlterField(
            model_name="dockerimage",
            name="state",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("pulling", "pulling"),
                    ("idle", "idle"),
                    ("deleting", "deleting"),
                    ("failed", "failed"),
                ],
                default="initial",
                help_text="The state of the image.",
                max_length=64,
            ),
        )
    ]
