# Generated by Django 3.1.8 on 2021-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containertemplates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertemplate',
            name='project',
        ),
        migrations.AlterField(
            model_name='containertemplate',
            name='title',
            field=models.CharField(help_text='Title of the container template.', max_length=512, unique=True),
        ),
    ]
