# Generated by Django 3.2.5 on 2021-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containertemplates', '0004_auto_20210706_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertemplateproject',
            name='inactivity_threshold',
            field=models.IntegerField(blank=True, default=7, help_text='Number of days the container is allowed to run without proxy access.', null=True),
        ),
        migrations.AddField(
            model_name='containertemplatesite',
            name='inactivity_threshold',
            field=models.IntegerField(blank=True, default=7, help_text='Number of days the container is allowed to run without proxy access.', null=True),
        ),
    ]
