# Generated by Django 3.2.5 on 2021-08-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containertemplates', '0005_auto_20210730_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertemplateproject',
            name='environment_secret_keys',
        ),
        migrations.RemoveField(
            model_name='containertemplatesite',
            name='environment_secret_keys',
        ),
    ]
