# Generated by Django 5.2.11 on 2026-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('containertemplates', '0007_auto_20220414_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertemplateproject',
            name='registry_password',
            field=models.CharField(
                blank=True,
                help_text='The password or token for the container registry, if it is a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='containertemplateproject',
            name='registry_user',
            field=models.CharField(
                blank=True,
                help_text='The user name for the container registry, if it is e.g. a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='containertemplatesite',
            name='registry_password',
            field=models.CharField(
                blank=True,
                help_text='The password or token for the container registry, if it is a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='containertemplatesite',
            name='registry_user',
            field=models.CharField(
                blank=True,
                help_text='The user name for the container registry, if it is e.g. a private Gitlab registry.',
                max_length=512,
                null=True,
            ),
        ),
    ]
