# Generated by Django 5.2.11 on 2026-06-17 08:52

from django.db import migrations


def create_default_template(apps, schema_editor):
    ContainerTemplateSite = apps.get_model(
        'containertemplates', 'ContainerTemplateSite'
    )
    ContainerTemplateSite.objects.create(
        title='Example Shiny App',
        description='https://rocker-project.org/images/versioned/shiny.html',
        repository='rocker/shiny',
        tag='4.6',
        container_port=3838,
    )


def remove_default_template(apps, schema_editor):
    ContainerTemplateSite = apps.get_model(
        'containertemplates', 'ContainerTemplateSite'
    )
    ContainerTemplateSite.objects.filter(title='Example Shiny App').delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            'containertemplates',
            '0008_alter_containertemplateproject_unique_together_and_more',
        ),
    ]

    operations = [
        migrations.RunPython(create_default_template, remove_default_template)
    ]
