# Generated by Django 5.2.11 on 2026-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "containertemplates",
            "0008_containertemplateproject_registry_password_and_more",
        ),
        ("projectroles", "0039_remove_project_public_guest_access"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="containertemplateproject",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="containertemplatesite",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="containertemplateproject",
            constraint=models.UniqueConstraint(
                fields=("project", "title"),
                name="containertemplates_containertemplateproject_unique_project_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="containertemplateproject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("registry_password__isnull", False),
                        ("registry_user__isnull", False),
                    ),
                    models.Q(
                        ("registry_password__isnull", True),
                        ("registry_user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="containertemplates_containertemplateproject_registry_credentials_not_null_individually",
                violation_error_message="Registry user and password should either both be null or both be specified, you cannot leave blank only one of them.",
            ),
        ),
        migrations.AddConstraint(
            model_name="containertemplatesite",
            constraint=models.UniqueConstraint(
                fields=("title",),
                name="containertemplates_containertemplatesite_unique_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="containertemplatesite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("registry_password__isnull", False),
                        ("registry_user__isnull", False),
                    ),
                    models.Q(
                        ("registry_password__isnull", True),
                        ("registry_user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="containertemplates_containertemplatesite_registry_credentials_not_null_individually",
                violation_error_message="Registry user and password should either both be null or both be specified, you cannot leave blank only one of them.",
            ),
        ),
    ]
