# Generated by Django 5.2.17 on 2026-08-06 15:44

import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('containertemplates', '0009_create_default_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertemplateproject',
            name='description',
            field=martor.models.MartorField(
                blank=True,
                help_text='Description of the container template (Markdown supported).',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='containertemplatesite',
            name='description',
            field=martor.models.MartorField(
                blank=True,
                help_text='Description of the container template (Markdown supported).',
                null=True,
            ),
        ),
    ]
